### ISSUE TITLE
world version is 177

### ISSUE THREAD

**Issue by lllXlll** [spinclick/wldquery#1]
so it doesn't work for current worlds, can you update it for the new format? thanks!

**Comment by lllXlll** [comment]
and absoltue paths give a issue, it states the syntax would be false. using all relative without quotes works though (like wldquery world.wld world_id output.txt)

**Comment by jnlon** [comment]
Looks like there are some new keys added to the header. I'm pretty busy this weekend, but I should be able to make a new release sometime this week with support for it.

**Comment by lllXlll** [comment]
alright, take your time! thx for fulfilling this and working on such awesome terraria tools. your ascii tool will also benefit from the update i'm sure

**Comment by jnlon** [comment]
The [new release](https://github.com/spinclick/wldquery/releases/tag/v.02) should do what you need
